
  server:
    port: 8083

  spring:
    application:
      name: ORDER-SERVICE

    kafka:
            bootstrap-servers: localhost:9092
            consumer:
              group-id: order-group

              auto-offset-reset: earliest

              key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
              value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
              producer:
                key-serializer: org.apache.kafka.common.serialization.StringSerializer
                value-serializer: org.apache.kafka.common.serialization.StringSerializer
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka

  resilience4j:
    circuitbreaker:
      instances:

        userServiceCircuitBreaker:

          registerHealthIndicator: true

          slidingWindowSize: 5

          minimumNumberOfCalls: 5

          failureRateThreshold: 50

          waitDurationInOpenState: 10s

          permittedNumberOfCallsInHalfOpenState: 2

          automaticTransitionFromOpenToHalfOpenEnabled: true



